workflows:
  default-workflow:
    name: Compilar APK Titaktak
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Crear proyecto Android
        script: flutter create . --platforms=android
      - name: Limpiar proyecto
        script: flutter clean
      - name: Instalar dependencias
        script: flutter pub get
      - name: Construir APK
        script: flutter build apk --release --build-name=1.0.0 --build-number=1
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk-release.apk
