workflows:
  default-workflow:
    name: Compilación Titaktak
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Generar estructura de Android
        script: flutter create . --platforms=android
      - name: Obtener dependencias
        script: flutter pub get
      - name: Construir APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
